services:
  rest-api:
    build:
      context: ./
    volumes:
      - .:/go/src/tekab-test
    ports:
      - "8080:8080"
    depends_on:
      - mysql_rest
    networks:
      - rest-api
    container_name: my-go-app


  mysql_rest:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=tekabTest
      - MYSQL_USER=rest_default
      - MYSQL_PASSWORD=8z7bf64Qi1
      - MYSQL_ROOT_PASSWORD=dnVh9M9g3Q
      - MYSQL_TCP_PORT=3306
    volumes:
    - ./test:/var/lib/mysql:rw
    - .:/docker-entrypoint-initdb.d/:ro
    networks:
      - rest-api
    restart: always
    ports:
      - 3308:3308
    container_name: mysql-app


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql_rest
    networks:
      - rest-api
    ports:
      - "7011:80"
    depends_on:
      - mysql_rest
    restart: always
    container_name: phpmyadmin-app
networks:
  rest-api:
    name: rest-api
    external: true


