basePath: /api
definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.Answer:
    properties:
      candidat_id:
        type: integer
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      point:
        type: integer
      test_id:
        type: integer
      updatedAt:
        type: string
    required:
    - candidat_id
    - point
    - test_id
    type: object
  models.Question:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      difficulty:
        type: string
      expected_time:
        type: integer
      file_read_me:
        type: string
      id:
        type: integer
      name:
        type: string
      points:
        type: integer
      question_text:
        type: string
      skill_id:
        type: integer
      test_questions:
        items:
          $ref: '#/definitions/models.TestQuestion'
        type: array
      type:
        type: string
      updatedAt:
        type: string
    required:
    - difficulty
    - expected_time
    - name
    - points
    type: object
  models.TestQuestion:
    properties:
      answer:
        items:
          $ref: '#/definitions/models.Answer'
        type: array
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      question_id:
        type: integer
      test_id:
        type: integer
      updatedAt:
        type: string
    required:
    - question_id
    - test_id
    type: object
info:
  contact: {}
  description: This is an application web of interview assessment tests for interviewing
    out of the box .
  version: "1.0"
paths:
  /questions:
    post:
      consumes:
      - application/json
      description: create new question by json
      parameters:
      - description: Add question
        in: body
        name: question
        required: true
        schema:
          $ref: '#/definitions/models.Question'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Question'
      security:
      - Authorization: []
      summary: add new  question
      tags:
      - question
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
